inputs: assets/PBA
outputs: outputs/PBA
visualize: True
merge2markdown: True
tasks:
  layout_detection:
    model: layout_detection_yolo
    model_config:
      img_size: 1024
      conf_thres: 0.25
      iou_thres: 0.45
      model_path: models/Layout/YOLO/doclayout_yolo_ft.pt
  formula_detection:
    model: formula_detection_yolo
    model_config:
      img_size: 1280
      conf_thres: 0.25
      iou_thres: 0.45
      batch_size: 1
      model_path: models/MFD/YOLO/yolo_v8_ft.pt
  formula_recognition:
    model: formula_recognition_unimernet
    model_config:
      batch_size: 128
      cfg_path: pdf_extract_kit/configs/unimernet.yaml
      model_path: models/MFR/unimernet_tiny
  table_parsing:
    model: table_parsing_struct_eqtable
    model_config:
      model_path: U4R/StructTable-InternVL2-1B
      max_new_tokens: 1024
      max_time: 30
      output_format: markdown
      lmdeploy: False
      flash_attn: False
  ocr:
    model: ocr_ppocr
    model_config:
      lang: en
      show_log: True
      det_model_dir: models/OCR/PaddleOCR/det/en_PP-OCRv4_det
      rec_model_dir: models/OCR/PaddleOCR/rec/en_PP-OCRv4_rec
      det_db_box_thresh: 0.3

  
